name: Run sum.py

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  run-sum:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run sum.py
      run: python sum.py
